Html and object
ut-code/utcode-learn pull request #189
Opened 2023-03-04 07:32 UTC by RRRyoma

lecture2,3の課題まで完成

2023-03-04 07:49 UTC, chvmvd commented
あ、ちなみにわざわざ Pull request をクローズしなくてもプッシュし直せば大丈夫ですよw

2023-03-04 08:11 UTC, kazukinumazato commented on src/pages/exercise/ryoma/index.md
> +//佐藤と鈴木を比べる→高橋と「佐藤＆鈴木」を比べる→田中と「佐藤＆鈴木＆高橋」を比べる
これ何ソートっていうんやっけ

2023-03-04 08:16 UTC, RRRyoma commented on src/pages/exercise/ryoma/index.md
> +//佐藤と鈴木を比べる→高橋と「佐藤＆鈴木」を比べる→田中と「佐藤＆鈴木＆高橋」を比べる
バブルソートやな

2023-03-04 08:18 UTC, RRRyoma commented on src/pages/exercise/lecture3/object-event/index.md
> +- ただし、javascriptは`tanaka`オブジェクトのみを参照する。新しい成績格納オブジェクトを作ってはならない。つまり、`tanaka`オブジェクトの点数プロパティをDOMで直接書き換えること!
50行目でtextContent書き換えてるよ

2023-03-04 08:19 UTC, kazukinumazato commented on src/pages/exercise/lecture3/object-event/index.md
> +- ただし、javascriptは`tanaka`オブジェクトのみを参照する。新しい成績格納オブジェクトを作ってはならない。つまり、`tanaka`オブジェクトの点数プロパティをDOMで直接書き換えること!
それは点数プロパティの書き換えではなくてdivのtextContentの書き換えじゃない？

2023-03-04 08:20 UTC, kazukinumazato commented on src/pages/exercise/lecture3/object-event/index.md
> +- ただし、javascriptは`tanaka`オブジェクトのみを参照する。新しい成績格納オブジェクトを作ってはならない。つまり、`tanaka`オブジェクトの点数プロパティをDOMで直接書き換えること!
プロパティの書き換え自体はDOM使う必要ないと思うぞ

2023-03-04 08:24 UTC, RRRyoma commented on src/pages/exercise/lecture3/object-event/index.md
> +- ただし、javascriptは`tanaka`オブジェクトのみを参照する。新しい成績格納オブジェクトを作ってはならない。つまり、`tanaka`オブジェクトの点数プロパティをDOMで直接書き換えること!
オブジェクトのプロパティ変更（tanakaの点数の書き換え）の練習が47,48行目で、イベント発生（ボタンクリックでtextContent書き換え）が50行目
両方一気に練習できるっていう問題やねんけど、わかりにくいかな

2023-03-04 08:25 UTC, RRRyoma commented on src/pages/exercise/ryoma/index.md
> +//佐藤と鈴木を比べる→高橋と「佐藤＆鈴木」を比べる→田中と「佐藤＆鈴木＆高橋」を比べる
気が向いたら外部サイトのリンク追加します

2023-03-04 08:26 UTC, kazukinumazato commented on src/pages/exercise/lecture3/object-event/index.md
> +- ただし、javascriptは`tanaka`オブジェクトのみを参照する。新しい成績格納オブジェクトを作ってはならない。つまり、`tanaka`オブジェクトの点数プロパティをDOMで直接書き換えること!
すくなくとも「`tanaka`オブジェクトの点数プロパティをDOMで直接書き換えること!」はおかしい

2023-03-04 08:26 UTC, RRRyoma commented on src/pages/exercise/lecture3/object-event/index.md
> +- ただし、javascriptは`tanaka`オブジェクトのみを参照する。新しい成績格納オブジェクトを作ってはならない。つまり、`tanaka`オブジェクトの点数プロパティをDOMで直接書き換えること!
textContentが変わるときにtanaka.scoresを参照してるから、DOMで書き換えるっていう言い方をしてる

2023-03-04 08:27 UTC, kazukinumazato commented on src/pages/exercise/lecture3/object-event/index.md
> +- ただし、javascriptは`tanaka`オブジェクトのみを参照する。新しい成績格納オブジェクトを作ってはならない。つまり、`tanaka`オブジェクトの点数プロパティをDOMで直接書き換えること!
ああ、コードの話じゃなくて問題文の話ね

2023-03-04 08:51 UTC, chvmvd requested changes
とりあえず、途中までです。
課題の内容はとてもおもしろいです。~~成績の改竄www~~

2023-03-04 08:51 UTC, chvmvd commented on src/pages/exercise/lecture3/object-event/index.md
> +- ただし、javascriptは`tanaka`オブジェクトのみを参照する。新しい成績格納オブジェクトを作ってはならない。つまり、`tanaka`オブジェクトの点数プロパティをDOMで直接書き換えること!
javascript => JavaScript
html => HTML
の方が良いかもです。これは、細かすぎですが。

2023-03-04 08:51 UTC, chvmvd commented on src/pages/exercise/lecture3/object-event/index.md
> +  <div id="academicPerformance">成績:数学...80点、理科...90点</div>
HTML 中の id 名や class 名は、ut.code(); Learn ではケバブケースで書いてるので、統一した方が良いかもしれませんね。
正直、これはケバブケースで書く派とキャメルケースで書く派で論争が続いてる話なので、微妙な話ですが。正解がない話なので、教材に合わせるのが安全な気がしています。

2023-03-04 08:51 UTC, chvmvd commented on src/pages/exercise/lecture3/object-event/index.md
> +function falsify_data() {
これも命名規則の話ですが、教材だと JavaScript の関数名はスネークケースではなくキャメルケースを使ってるので、そっちに合わせた方が良いかもしれません。

2023-03-04 08:51 UTC, chvmvd commented on src/pages/exercise/lecture3/object-event/index.md
> +  academicPerformance.textContent = `成績:数学...${tanaka.scores.math}点、理科...${tanaka.scores.science}点`
テンプレートリテラルは[繰り返しのセクション](https://learn.utcode.net/docs/browser-apps/loop/#%E3%83%8D%E3%82%B9%E3%83%88%E3%81%95%E3%82%8C%E3%81%9F%E3%83%AB%E3%83%BC%E3%83%97)が初出なので、この時点だとまだ習ってない気がします。`+` 演算子で繋げる感じで良いかと思います。~~`+` 演算子で繋げると ESLint だと怒られたりしますが、気にしない。~~

2023-03-04 08:51 UTC, chvmvd commented on src/pages/exercise/ryoma/index.md
> +~~~ javascript
````markdown
- `math` , `science`の合計点が高い者を上位とする。
- 上記で同率になった場合、`math`の得点が高い者を上位とする。
- 順位の判定はもちろん、配列内で繰り返し処理（点数の比較）をするプログラムをjavascriptで書いて行う。

  ~~~ javascript
  let academicPerformanceData = [sato, suzuki, takahashi, tanaka];
  //let academicPerformanceData = [tanaka, suzuki, sato, takahashi];などでも構わない。
  //for文でacademicPerformanceDataの要素を順位順に並べ替える処理を書く
  ~~~

- 最初の配列`academicPerformanceData`がどんな並びをしていても,最終的には1位から順に並んだ配列が出てくるようにプログラムを作成すること。(上記の点数の場合は`[suzuki, tanaka, sato, takahashi]`)
````
こんな感じにすれば Codeblock にインデントをつけられます。
後、最後の箇条書きが箇条書きになっておらず仲間外れになっててかわいそうな気もしてます。

2023-03-04 08:51 UTC, chvmvd commented on src/pages/exercise/ryoma/index.md
> +~~~ javascript
最後の 2 つはほぼ自明な気もしますが。

2023-03-04 08:51 UTC, chvmvd commented on src/pages/exercise/ryoma/index.md
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0">
これは[CSS による配置のセクション](https://learn.utcode.net/docs/browser-apps/css-arrangement/#%E3%83%AC%E3%82%B9%E3%83%9D%E3%83%B3%E3%82%B7%E3%83%96%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3)が初出なので、まだ習ってない気がします。

一個上のは触れてる項がないので…~~説明書きたくない~~

2023-03-04 08:51 UTC, chvmvd commented on src/pages/exercise/ryoma/index.md
> +//データオブジェクトを生成
これこそクラスの出番のような気がw
~~僕がクラス使いこなせていないから、わかんないけど~~

2023-03-04 08:51 UTC, chvmvd commented on src/pages/exercise/ryoma/index.md
> +let academicPerformanceData = [sato, suzuki, takahashi, tanaka];
`const` でも動くか？

2023-03-04 08:51 UTC, chvmvd commented on src/pages/exercise/ryoma/index.md
> +function swap(a, b) {
ここは、人口に膾炙したこんなコードの方が良いかも？
```javascript
const tmp = academicPerformanceData[a];
academicPerformanceData[a] = academicPerformanceData[b];
academicPerformanceData[b] = tmp;
```

2023-03-04 08:51 UTC, chvmvd commented on src/pages/exercise/ryoma/index.md
> +for (let i = 1; i < 4; i++) {
`i++` って教材にありましたっけ？
なかったら、教材に追加した方が良いかもしれませんね。

2023-03-04 08:51 UTC, chvmvd commented on src/pages/exercise/ryoma/index.txt
> +# 課題１（配列・繰り返し）
拡張子が Markdown じゃなくてみれないよう(泣)

2023-03-04 08:51 UTC, chvmvd commented on src/pages/exercise/lecture3/object-event/index.md
> +しかしながら田中君は、親にmath,scienceの成績を高く見せたいと考えました。
成績の改竄wwwwww
プログラミングをやってると、やりたくなるwww

2023-03-04 08:53 UTC, chvmvd commented on src/pages/exercise/ryoma/index.md
> +//佐藤と鈴木を比べる→高橋と「佐藤＆鈴木」を比べる→田中と「佐藤＆鈴木＆高橋」を比べる
バブルソート以外は地獄なので、やめたほうがよいかもしれないです。

2023-03-04 08:55 UTC, chvmvd commented on src/pages/exercise/ryoma/index.md
> +//佐藤と鈴木を比べる→高橋と「佐藤＆鈴木」を比べる→田中と「佐藤＆鈴木＆高橋」を比べる
授業一回分あるので。
僕もシケプリ書く時に、諦めたぐらいなので。まあ、「バブルソート以外にもさまざまなソートがあります。」とだけ言っておくのはありかもしれない。
https://sikepuri-algorithm.github.io/docs/algorithms/sort/

2023-03-04 09:01 UTC, RRRyoma commented on src/pages/exercise/lecture3/object-event/index.md
> +しかしながら田中君は、親にmath,scienceの成績を高く見せたいと考えました。
なおしましたー

2023-03-04 09:01 UTC, RRRyoma commented on src/pages/exercise/lecture3/object-event/index.md
> +- ただし、javascriptは`tanaka`オブジェクトのみを参照する。新しい成績格納オブジェクトを作ってはならない。つまり、`tanaka`オブジェクトの点数プロパティをDOMで直接書き換えること!
なおしましたー

2023-03-04 09:02 UTC, RRRyoma commented on src/pages/exercise/lecture3/object-event/index.md
> +  <div id="academicPerformance">成績:数学...80点、理科...90点</div>
なおしましたー

2023-03-04 09:02 UTC, RRRyoma commented on src/pages/exercise/lecture3/object-event/index.md
> +function falsify_data() {
なおしましたー

2023-03-04 09:02 UTC, RRRyoma commented on src/pages/exercise/lecture3/object-event/index.md
> +  academicPerformance.textContent = `成績:数学...${tanaka.scores.math}点、理科...${tanaka.scores.science}点`
テンプレートリテラル紹介するのを早めるのはどうでしょう

2023-03-04 09:03 UTC, RRRyoma commented on src/pages/exercise/ryoma/index.md
> +function swap(a, b) {
直感的に分かりやすいかなーと思ったけど、そっちのほうがええかなあ

2023-03-04 09:03 UTC, chvmvd commented on src/pages/exercise/lecture3/object-event/index.md
> +- ただし、javascriptは`tanaka`オブジェクトのみを参照する。新しい成績格納オブジェクトを作ってはならない。つまり、`tanaka`オブジェクトの点数プロパティをDOMで直接書き換えること!
たしかに、問題文はおかしかったか。書き換えたのは、textContent だね。

2023-03-04 09:05 UTC, chvmvd commented on src/pages/exercise/lecture3/object-event/index.md
> +  academicPerformance.textContent = `成績:数学...${tanaka.scores.math}点、理科...${tanaka.scores.science}点`
どうなんだろう。そんな気もする。

2023-03-04 09:06 UTC, chvmvd commented on src/pages/exercise/lecture3/object-event/index.md
> +  academicPerformance.textContent = `成績:数学...${tanaka.scores.math}点、理科...${tanaka.scores.science}点`
でも、新歓体験会のところが情報過多になるから、後ろにずらしたって説はある。
僕的にはもうちょっとはやく知りたいけど。

2023-03-04 09:07 UTC, RRRyoma commented on src/pages/exercise/ryoma/index.txt
> +# 課題１（配列・繰り返し）
ただのメモ書きやから無視してほしい

2023-03-04 09:08 UTC, chvmvd commented on src/pages/exercise/lecture3/object-event/index.md
> +しかしながら田中君は、親にmath,scienceの成績を高く見せたいと考えました。
ありがとう！

2023-03-04 09:08 UTC, RRRyoma commented on src/pages/exercise/ryoma/index.md
> +for (let i = 1; i < 4; i++) {
i++の説明追加しときました

2023-03-04 09:08 UTC, chvmvd commented on src/pages/exercise/lecture3/object-event/index.md
> +- ただし、javascriptは`tanaka`オブジェクトのみを参照する。新しい成績格納オブジェクトを作ってはならない。つまり、`tanaka`オブジェクトの点数プロパティをDOMで直接書き換えること!
ありがとう！

2023-03-04 09:08 UTC, chvmvd commented on src/pages/exercise/lecture3/object-event/index.md
> +  <div id="academicPerformance">成績:数学...80点、理科...90点</div>
ありがとう！！

2023-03-04 09:10 UTC, chvmvd commented on src/pages/exercise/ryoma/index.md
> +function swap(a, b) {
正直、あそこまで変数は用意しなくて良い気はする。

2023-03-04 09:12 UTC, chvmvd commented on src/pages/exercise/ryoma/index.txt
> +# 課題１（配列・繰り返し）
了解。

2023-03-04 09:13 UTC, chvmvd commented on src/pages/exercise/ryoma/index.md
> +for (let i = 1; i < 4; i++) {
了解。

2023-03-04 09:14 UTC, chvmvd commented on src/pages/exercise/lecture3/object-event/index.md
> +function falsify_data() {
了解。

2023-03-04 09:18 UTC, chvmvd commented on src/pages/exercise/ryoma/index.txt
> +# 課題１（配列・繰り返し）
作業途中だったら、ここから Pull request を Draft にすることができたり。そうすると、Draft の間はレビューが飛んでこなくなる。
<img width="349" alt="スクリーンショット 2023-03-04 18 17 36" src="https://user-images.githubusercontent.com/104971044/222890116-5ce7c859-fbc1-4bcb-b2ab-dcab7ab22a99.png">

2023-03-04 09:33 UTC, RRRyoma commented on src/pages/exercise/ryoma/index.md
> +//データオブジェクトを生成
最初クラスも考えたけど、成績オブジェクトに使うメソッドが特に無いから、関数でいいやとなった

2023-03-04 09:34 UTC, RRRyoma commented on src/pages/exercise/ryoma/index.md
> +let academicPerformanceData = [sato, suzuki, takahashi, tanaka];
動くよ～

2023-03-04 09:35 UTC, RRRyoma commented on src/pages/exercise/ryoma/index.md
> +function swap(a, b) {
swapは二通り書いときました

2023-03-04 09:36 UTC, RRRyoma commented on src/pages/exercise/ryoma/index.txt
> +# 課題１（配列・繰り返し）
その画像のページはどうやって開けるの？

2023-03-04 09:37 UTC, RRRyoma commented on src/pages/exercise/ryoma/index.md
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0">
うわああ
（vscodeで「！」→tabでひな形を作れるのでそのまんま使ってるんすよ...）

2023-03-04 09:44 UTC, chvmvd commented on src/pages/exercise/ryoma/index.txt
> +# 課題１（配列・繰り返し）
ここの画面の右上にある。

2023-03-05 03:56 UTC, kazukinumazato commented on src/pages/exercise/ryoma/index.md
> +let academicPerformanceData = [sato, suzuki, takahashi, tanaka];
const のほうがよろしいやろな

2023-03-05 03:57 UTC, kazukinumazato commented on src/pages/exercise/ryoma/index.md
> +let academicPerformanceData = [sato, suzuki, takahashi, tanaka];
基本的に配列はオブジェクトと同じく参照型なので配列そのものを再代入しない限りはconstのほうが良いです

2023-03-05 04:00 UTC, kazukinumazato approved these changes
あとは上のコメントにも書いてあるように let を const に変えるだけかね

2023-03-05 04:29 UTC, chvmvd commented on src/pages/exercise/ryoma/index.md
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0">
僕もそれ使ってて急いで消した記憶が…

2023-03-05 04:30 UTC, chvmvd commented on src/pages/exercise/ryoma/index.md
> +//データオブジェクトを生成
どうなんだろう。難しいな。

2023-03-05 04:31 UTC, chvmvd commented on src/pages/exercise/ryoma/index.md
> +function swap(a, b) {
別解にするほどのものでもない気はするから、消しちゃっていいよ。

2023-03-05 04:33 UTC, chvmvd commented
> あとは上のコメントにも書いてあるように let を const に変えるだけかね

ですね。

2023-03-05 10:29 UTC, RRRyoma commented
仰せの通りに直しときました

2023-03-05 10:29 UTC, RRRyoma commented
まちがってCloseしてもた

2023-03-05 10:42 UTC, merged