Add operator console
ut-code/utcode-learn pull request #191
Opened 2023-03-05 07:23 UTC by Yokomi422

演算子の説明を加えました。
console.log()の説明を「JavaScript」ことはじめに追加しました。ただ、他の章のdocument.write()はまだ変更していません。他の章のdocument.write()にもconsole.log()を並列させて書いた方がいいですか？

2023-03-05 07:37 UTC, chvmvd commented
PR 無事送れてよかった！

2023-03-05 07:41 UTC, kazukinumazato commented
cloudflare pagesが動いてねぇ…
手動でデプロイするのってどうやってやるんやっけ？

2023-03-05 07:42 UTC, kazukinumazato commented
すみません、動いてました

2023-03-05 07:49 UTC, kazukinumazato requested changes

2023-03-05 07:49 UTC, kazukinumazato commented on docs/1-trial-session/03-javascript/index.md
> +VSCodeのコンソールで実行してみましょう。`Hello World!`と表示されましたか？
初心者は多分コンソールとか開発者ツールとかよくわからないと思うので、document.writeと同じく動画とかつけたほうがいいような気がしますね

2023-03-05 07:49 UTC, kazukinumazato commented on docs/1-trial-session/04-expressions/index.md
> +| 演算子 | 説明 | 例
さすがに表がいきなり出てくるのは唐突すぎるので「代表的な演算子」とか何かしらの説明・前置きを入れたほうがいいと思います

2023-03-05 07:49 UTC, chvmvd commented on docs/1-trial-session/03-javascript/index.md
> +```document.write()```はブラウザ上に表示させます。一方、```console.log()```はブラウザには表示させず、開発者ツールのコンソールなど
実は、インラインコードは `` `document.write()` `` でも書けたり。

2023-03-05 07:49 UTC, chvmvd commented on docs/1-trial-session/04-expressions/index.md
> +|   `+` |　足す   | `1 + 1 === 2``"A" + "B" === "AB"`|
多分、ここが
`1 + 1 === 2``"A" + "B" === "AB"` 
こんな感じで表示されるから、間にスペースかなにか入れると良いかも。

2023-03-05 07:50 UTC, chvmvd commented on docs/1-trial-session/03-javascript/index.md
> +VSCodeのコンソールで実行してみましょう。`Hello World!`と表示されましたか？
そうですね。
[ここ](http://localhost:3000/docs/browser-apps/inspector/)の項で説明するのは、ありかも。

2023-03-05 07:52 UTC, chvmvd commented on docs/1-trial-session/04-expressions/index.md
> +| 演算子 | 説明 | 例
たしかに。
Markdown だと題名が入れられなかった気がするので、h3 とかで入れるのが良いかな。
```md
### 代表的な演算子
```
みたいな感じ？

2023-03-05 07:56 UTC, chvmvd commented on docs/1-trial-session/03-javascript/index.md
> +VSCodeのコンソールで実行してみましょう。`Hello World!`と表示されましたか？
あと、これって Node.js の話？僕がわかってないだけかもですが。
それと、開発者ツールはこのときまだ習っていない気が…

2023-03-05 08:02 UTC, kazukinumazato commented on docs/1-trial-session/03-javascript/index.md
> +VSCodeのコンソールで実行してみましょう。`Hello World!`と表示されましたか？
てかnode入れてないのでそもそもローカルでjsファイル実行できない気がしますね

2023-03-05 08:02 UTC, kazukinumazato commented on docs/1-trial-session/04-expressions/index.md
> +| 演算子 | 説明 | 例
超いい感じw

2023-03-05 08:28 UTC, chvmvd commented on docs/1-trial-session/03-javascript/index.md
> +VSCodeのコンソールで実行してみましょう。`Hello World!`と表示されましたか？
[これ](https://learn.utcode.net/docs/browser-apps/project/#-%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6-1)の話ですね。

<img width="828" alt="スクリーンショット 2023-03-05 17 27 11" src="https://user-images.githubusercontent.com/104971044/222950091-a33626d3-6e66-42d2-87e5-64fc03eef475.png">

2023-03-06 04:26 UTC, kazukinumazato commented on docs/1-trial-session/03-javascript/index.md
> +VSCodeのコンソールで実行してみましょう。`Hello World!`と表示されましたか？
なるほど、そういう使い方ならできそうですね

ただ、どっちにしろ開発者ツールがいるという…

2023-03-06 08:22 UTC, chvmvd commented on docs/1-trial-session/03-javascript/index.md
> +VSCodeのコンソールで実行してみましょう。`Hello World!`と表示されましたか？
ですね。
開発者ツールの説明のところに console.log の説明を加える感じが楽かな？
そしたら、新歓体験会の後からは console.log を使えるようになりますね。

2023-03-06 13:07 UTC, chvmvd commented on docs/1-trial-session/03-javascript/index.md
> +VSCodeのコンソールで実行してみましょう。`Hello World!`と表示されましたか？
https://github.com/ut-code/utcode-learn/blob/37bb86bcf2ecd2d48021718996a0cc460c75b4d4/docs/2-browser-apps/01-inspector/index.md?plain=1#L108
ここらへんにこんな感じで説明入れるのはどうですか？
````mdx
:::tip `console.log`

`console.log` 関数を用いて、 `Console` タブにメッセージを表示させることもできます。下のようなコードを作成してブラウザで開いてみましょう。`Console` タブを開くと、`Hello World!` と表示されているはずです。

```javascript title=script.js
console.log("Hello World!");
```

:::
````

2023-03-06 13:22 UTC, chvmvd commented on docs/1-trial-session/03-javascript/index.md
> +VSCodeのコンソールで実行してみましょう。`Hello World!`と表示されましたか？
https://user-images.githubusercontent.com/104971044/223121849-3eb4a82a-2e46-4806-98d5-fa7361523f45.mp4

動画もどうぞ。テキトーですが。

2023-03-06 13:23 UTC, kazukinumazato commented on docs/1-trial-session/03-javascript/index.md
> +VSCodeのコンソールで実行してみましょう。`Hello World!`と表示されましたか？
なるほど、tipならいいですね

2023-03-20 06:03 UTC, chvmvd commented on docs/1-trial-session/04-expressions/index.md
> +| 演算子 | 説明 | 例
#211 で解決

2023-03-20 06:09 UTC, chvmvd commented on docs/1-trial-session/03-javascript/index.md
> +```document.write()```はブラウザ上に表示させます。一方、```console.log()```はブラウザには表示させず、開発者ツールのコンソールなど
Fixed with #217

2023-03-20 06:10 UTC, chvmvd commented
#211 と #212 ですでに解決しているので、クローズします。

2023-03-20 06:10 UTC, closed without merging